apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  selector:
    matchLabels:
      app: profile-service
  replicas: 1
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: ayoobki/profile-service:latest
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: ClusterIP
  selector:
    app: profile-service
  ports:
    - port: 3002
      targetPort: 3002
